# Generated by Django 5.0.6 on 2024-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('unit user', 'Unit User'), ('head of department', 'Head of Department'), ('head of division', 'Head of Division')], default='user', max_length=20),
        ),
    ]
