# Generated by Django 5.0.6 on 2024-07-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('unituser', 'UnitUser'), ('head of department', 'HeadofDepartment'), ('head of division', 'HeadofDivision')], default='user', max_length=20),
        ),
    ]
